<?php

use Illuminate\Database\Seeder;

class CategoryAttributeValuesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('category_attribute_values')->insert([
            ['category_id' => 5, 'name' => 'Màu sắc'],
            ['category_id' => 6, 'name' => 'Màu sắc'],
            ['category_id' => 7, 'name' => 'Màu sắc'],
            ['category_id' => 8, 'name' => 'Màu sắc'],
            ['category_id' => 9, 'name' => 'Màu sắc'],
            ['category_id' => 10, 'name' => 'Màu sắc'],
            ['category_id' => 11, 'name' => 'Màu sắc'],
            ['category_id' => 12, 'name' => 'Màu sắc'],
            ['category_id' => 13, 'name' => 'Màu sắc'],
            ['category_id' => 13, 'name' => 'Kích thước màn hình'],
            ['category_id' => 14, 'name' => 'Màu sắc'],
            ['category_id' => 14, 'name' => 'Kích thước màn hình'],
            ['category_id' => 15, 'name' => 'Màu sắc'],
            ['category_id' => 15, 'name' => 'Kích thước màn hình'],
            ['category_id' => 16, 'name' => 'Màu sắc'],
            ['category_id' => 16, 'name' => 'Kích thước màn hình'],
            ['category_id' => 28, 'name' => 'Màu sắc'],
            ['category_id' => 28, 'name' => 'Kích thước'],
            ['category_id' => 29, 'name' => 'Màu sắc'],
            ['category_id' => 29, 'name' => 'Kích thước'],
            ['category_id' => 30, 'name' => 'Màu sắc'],
            ['category_id' => 30, 'name' => 'Kích thước'],
            ['category_id' => 31, 'name' => 'Màu sắc'],
            ['category_id' => 31, 'name' => 'Kích thước'],
            ['category_id' => 32, 'name' => 'Màu sắc'],
            ['category_id' => 32, 'name' => 'Kích thước'],
            ['category_id' => 33, 'name' => 'Màu sắc'],
            ['category_id' => 33, 'name' => 'Kích thước'],
            ['category_id' => 34, 'name' => 'Màu sắc'],
            ['category_id' => 34, 'name' => 'Kích thước'],
            ['category_id' => 35, 'name' => 'Màu sắc'],
            ['category_id' => 35, 'name' => 'Kích thước'],
            ['category_id' => 36, 'name' => 'Màu sắc'],
            ['category_id' => 36, 'name' => 'Kích thước'],
            ['category_id' => 37, 'name' => 'Màu sắc'],
            ['category_id' => 37, 'name' => 'Kích thước'],
            ['category_id' => 38, 'name' => 'Màu sắc'],
            ['category_id' => 38, 'name' => 'Kích thước'],
            ['category_id' => 39, 'name' => 'Màu sắc'],
            ['category_id' => 39, 'name' => 'Kích thước'],
            ['category_id' => 40, 'name' => 'Màu sắc'],
            ['category_id' => 40, 'name' => 'Kích thước'],
            ['category_id' => 41, 'name' => 'Màu sắc'],
            ['category_id' => 41, 'name' => 'Kích thước'],
            ['category_id' => 42, 'name' => 'Màu sắc'],
            ['category_id' => 42, 'name' => 'Kích thước'],
            ['category_id' => 48, 'name' => 'Màu sắc'],
            ['category_id' => 48, 'name' => 'Kích thước'],
            ['category_id' => 49, 'name' => 'Màu sắc'],
            ['category_id' => 49, 'name' => 'Kích thước'],
            ['category_id' => 50, 'name' => 'Màu sắc'],
            ['category_id' => 50, 'name' => 'Kích thước'],
            ['category_id' => 51, 'name' => 'Màu sắc'],
            ['category_id' => 51, 'name' => 'Kích thước'],
            ['category_id' => 52, 'name' => 'Màu sắc'],
            ['category_id' => 52, 'name' => 'Kích thước'],
            ['category_id' => 53, 'name' => 'Màu sắc'],
            ['category_id' => 53, 'name' => 'Kích thước'],
            ['category_id' => 54, 'name' => 'Màu sắc'],
            ['category_id' => 54, 'name' => 'Kích thước'],
            ['category_id' => 55, 'name' => 'Màu sắc'],
            ['category_id' => 55, 'name' => 'Kích thước'],
            ['category_id' => 56, 'name' => 'Màu sắc'],
            ['category_id' => 56, 'name' => 'Kích thước'],
            ['category_id' => 57, 'name' => 'Màu sắc'],
            ['category_id' => 57, 'name' => 'Kích thước'],
            ['category_id' => 58, 'name' => 'Màu sắc'],
            ['category_id' => 58, 'name' => 'Kích thước'],
            ['category_id' => 59, 'name' => 'Màu sắc'],
            ['category_id' => 59, 'name' => 'Kích thước'],
            ['category_id' => 60, 'name' => 'Màu sắc'],
            ['category_id' => 60, 'name' => 'Kích thước'],
            ['category_id' => 66, 'name' => 'Màu sắc'],
            ['category_id' => 66, 'name' => 'Kích thước'],
            ['category_id' => 67, 'name' => 'Màu sắc'],
            ['category_id' => 67, 'name' => 'Kích thước'],
            ['category_id' => 68, 'name' => 'Màu sắc'],
            ['category_id' => 68, 'name' => 'Kích thước'],
            ['category_id' => 69, 'name' => 'Màu sắc'],
            ['category_id' => 69, 'name' => 'Kích thước'],
            ['category_id' => 70, 'name' => 'Màu sắc'],
            ['category_id' => 70, 'name' => 'Kích thước'],
            ['category_id' => 71, 'name' => 'Màu sắc'],
            ['category_id' => 71, 'name' => 'Kích thước'],
            ['category_id' => 72, 'name' => 'Màu sắc'],
            ['category_id' => 72, 'name' => 'Kích thước'],
            ['category_id' => 73, 'name' => 'Màu sắc'],
            ['category_id' => 73, 'name' => 'Kích thước'],
            ['category_id' => 74, 'name' => 'Màu sắc'],
            ['category_id' => 74, 'name' => 'Kích thước'],
            ['category_id' => 75, 'name' => 'Màu sắc'],
            ['category_id' => 75, 'name' => 'Kích thước'],
            ['category_id' => 76, 'name' => 'Màu sắc'],
            ['category_id' => 76, 'name' => 'Kích thước'],
            ['category_id' => 77, 'name' => 'Màu sắc'],
            ['category_id' => 77, 'name' => 'Kích thước']
        ]);
    }
}
