<?php

use Illuminate\Database\Seeder;

class ProductAttributeValuesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product_attribute_values')->insert([
            ['product_id' => 1, 'category_attribute_value_id' => 1, 'value' => 'Trắng'],
            ['product_id' => 1, 'category_attribute_value_id' => 1, 'value' => 'Đỏ'],
            ['product_id' => 1, 'category_attribute_value_id' => 1, 'value' => 'Đen'],
            ['product_id' => 2, 'category_attribute_value_id' => 2, 'value' => 'Trắng'],
            ['product_id' => 2, 'category_attribute_value_id' => 2, 'value' => 'Đỏ'],
            ['product_id' => 2, 'category_attribute_value_id' => 2, 'value' => 'Đen'],
            ['product_id' => 3, 'category_attribute_value_id' => 17, 'value' => 'Trắng'],
            ['product_id' => 3, 'category_attribute_value_id' => 17, 'value' => 'Nâu'],
            ['product_id' => 3, 'category_attribute_value_id' => 17, 'value' => 'Đen'],
            ['product_id' => 3, 'category_attribute_value_id' => 18, 'value' => 'L'],
            ['product_id' => 3, 'category_attribute_value_id' => 18, 'value' => 'XL'],
            ['product_id' => 3, 'category_attribute_value_id' => 18, 'value' => 'XXL'],
            ['product_id' => 4, 'category_attribute_value_id' => 19, 'value' => 'Xanh'],
            ['product_id' => 4, 'category_attribute_value_id' => 19, 'value' => 'Nâu'],
            ['product_id' => 4, 'category_attribute_value_id' => 19, 'value' => 'Đen'],
            ['product_id' => 4, 'category_attribute_value_id' => 20, 'value' => 'L'],
            ['product_id' => 4, 'category_attribute_value_id' => 20, 'value' => 'XL'],
            ['product_id' => 4, 'category_attribute_value_id' => 20, 'value' => 'XXL'],
            ['product_id' => 5, 'category_attribute_value_id' => 23, 'value' => 'Trắng'],
            ['product_id' => 5, 'category_attribute_value_id' => 23, 'value' => 'Xanh'],
            ['product_id' => 5, 'category_attribute_value_id' => 23, 'value' => 'Đen'],
            ['product_id' => 5, 'category_attribute_value_id' => 24, 'value' => 'M'],
            ['product_id' => 5, 'category_attribute_value_id' => 24, 'value' => 'L'],
            ['product_id' => 5, 'category_attribute_value_id' => 24, 'value' => 'XL'],
            ['product_id' => 6, 'category_attribute_value_id' => 25, 'value' => 'Trắng'],
            ['product_id' => 6, 'category_attribute_value_id' => 25, 'value' => 'Đen'],
            ['product_id' => 6, 'category_attribute_value_id' => 25, 'value' => 'Xanh'],
            ['product_id' => 6, 'category_attribute_value_id' => 26, 'value' => 'M'],
            ['product_id' => 6, 'category_attribute_value_id' => 26, 'value' => 'L'],
            ['product_id' => 6, 'category_attribute_value_id' => 26, 'value' => 'XL'],
            ['product_id' => 7, 'category_attribute_value_id' => 25, 'value' => 'Trắng'],
            ['product_id' => 7, 'category_attribute_value_id' => 25, 'value' => 'Xanh'],
            ['product_id' => 7, 'category_attribute_value_id' => 25, 'value' => 'Đen'],
            ['product_id' => 7, 'category_attribute_value_id' => 26, 'value' => 'M'],
            ['product_id' => 7, 'category_attribute_value_id' => 26, 'value' => 'L'],
            ['product_id' => 7, 'category_attribute_value_id' => 26, 'value' => 'XL'],
            ['product_id' => 8, 'category_attribute_value_id' => 27, 'value' => 'Trắng'],
            ['product_id' => 8, 'category_attribute_value_id' => 27, 'value' => 'Nâu'],
            ['product_id' => 8, 'category_attribute_value_id' => 27, 'value' => 'Xanh'],
            ['product_id' => 8, 'category_attribute_value_id' => 28, 'value' => 'L'],
            ['product_id' => 8, 'category_attribute_value_id' => 28, 'value' => 'XL'],
            ['product_id' => 8, 'category_attribute_value_id' => 28, 'value' => 'XXL'],
            ['product_id' => 9, 'category_attribute_value_id' => 29, 'value' => 'Trắng'],
            ['product_id' => 9, 'category_attribute_value_id' => 29, 'value' => 'Đen'],
            ['product_id' => 9, 'category_attribute_value_id' => 29, 'value' => 'Đỏ'],
            ['product_id' => 9, 'category_attribute_value_id' => 30, 'value' => 'M'],
            ['product_id' => 9, 'category_attribute_value_id' => 30, 'value' => 'L'],
            ['product_id' => 9, 'category_attribute_value_id' => 30, 'value' => 'XL'],
            ['product_id' => 10, 'category_attribute_value_id' => 29, 'value' => 'Đen'],
            ['product_id' => 10, 'category_attribute_value_id' => 29, 'value' => 'Xanh'],
            ['product_id' => 10, 'category_attribute_value_id' => 29, 'value' => 'Vàng'],
            ['product_id' => 10, 'category_attribute_value_id' => 30, 'value' => 'L'],
            ['product_id' => 10, 'category_attribute_value_id' => 30, 'value' => 'XL'],
            ['product_id' => 10, 'category_attribute_value_id' => 30, 'value' => 'XXL'],
            ['product_id' => 11, 'category_attribute_value_id' => 33, 'value' => 'Xám'],
            ['product_id' => 11, 'category_attribute_value_id' => 34, 'value' => '29'],
            ['product_id' => 11, 'category_attribute_value_id' => 34, 'value' => '30'],
            ['product_id' => 11, 'category_attribute_value_id' => 34, 'value' => '31'],
            ['product_id' => 11, 'category_attribute_value_id' => 34, 'value' => '32'],
            ['product_id' => 11, 'category_attribute_value_id' => 34, 'value' => '33'],
            ['product_id' => 12, 'category_attribute_value_id' => 33, 'value' => 'Đen'],
            ['product_id' => 12, 'category_attribute_value_id' => 33, 'value' => 'Xanh'],
            ['product_id' => 12, 'category_attribute_value_id' => 33, 'value' => 'Xanh Đậm'],
            ['product_id' => 12, 'category_attribute_value_id' => 34, 'value' => '30'],
            ['product_id' => 12, 'category_attribute_value_id' => 34, 'value' => '31'],
            ['product_id' => 12, 'category_attribute_value_id' => 34, 'value' => '32'],
            ['product_id' => 13, 'category_attribute_value_id' => 39, 'value' => 'Nâu'],
            ['product_id' => 13, 'category_attribute_value_id' => 39, 'value' => 'Trắng'],
            ['product_id' => 13, 'category_attribute_value_id' => 40, 'value' => '30'],
            ['product_id' => 13, 'category_attribute_value_id' => 40, 'value' => '31'],
            ['product_id' => 13, 'category_attribute_value_id' => 40, 'value' => '32'],
            ['product_id' => 14, 'category_attribute_value_id' => 37, 'value' => 'Trắng'],
            ['product_id' => 14, 'category_attribute_value_id' => 37, 'value' => 'Xanh'],
            ['product_id' => 14, 'category_attribute_value_id' => 38, 'value' => '30'],
            ['product_id' => 14, 'category_attribute_value_id' => 38, 'value' => '31'],
            ['product_id' => 14, 'category_attribute_value_id' => 38, 'value' => '32'],
            ['product_id' => 15, 'category_attribute_value_id' => 47, 'value' => 'Đen'],
            ['product_id' => 15, 'category_attribute_value_id' => 47, 'value' => 'Đỏ'],
            ['product_id' => 15, 'category_attribute_value_id' => 48, 'value' => 'Free Size'],
            ['product_id' => 16, 'category_attribute_value_id' => 49, 'value' => 'Trắng'],
            ['product_id' => 16, 'category_attribute_value_id' => 49, 'value' => 'Đỏ'],
            ['product_id' => 16, 'category_attribute_value_id' => 49, 'value' => 'Hồng'],
            ['product_id' => 16, 'category_attribute_value_id' => 50, 'value' => 'Free Size'],
            ['product_id' => 17, 'category_attribute_value_id' => 51, 'value' => 'Trắng'],
            ['product_id' => 17, 'category_attribute_value_id' => 51, 'value' => 'Xanh'],
            ['product_id' => 17, 'category_attribute_value_id' => 51, 'value' => 'Đen'],
            ['product_id' => 17, 'category_attribute_value_id' => 52, 'value' => 'Free Size'],
            ['product_id' => 18, 'category_attribute_value_id' => 51, 'value' => 'Trắng'],
            ['product_id' => 18, 'category_attribute_value_id' => 51, 'value' => 'Xanh'],
            ['product_id' => 18, 'category_attribute_value_id' => 51, 'value' => 'Hồng'],
            ['product_id' => 18, 'category_attribute_value_id' => 52, 'value' => 'Free Size'],
            ['product_id' => 19, 'category_attribute_value_id' => 53, 'value' => 'Xanh'],
            ['product_id' => 19, 'category_attribute_value_id' => 53, 'value' => 'Đen'],
            ['product_id' => 19, 'category_attribute_value_id' => 54, 'value' => 'M'],
            ['product_id' => 19, 'category_attribute_value_id' => 54, 'value' => 'L'],
            ['product_id' => 20, 'category_attribute_value_id' => 55, 'value' => 'Xanh'],
            ['product_id' => 20, 'category_attribute_value_id' => 55, 'value' => 'Đen'],
            ['product_id' => 20, 'category_attribute_value_id' => 56, 'value' => 'L'],
            ['product_id' => 20, 'category_attribute_value_id' => 56, 'value' => 'XL'],
            ['product_id' => 21, 'category_attribute_value_id' => 55, 'value' => 'Xanh'],
            ['product_id' => 21, 'category_attribute_value_id' => 55, 'value' => 'Đen'],
            ['product_id' => 21, 'category_attribute_value_id' => 56, 'value' => 'L'],
            ['product_id' => 21, 'category_attribute_value_id' => 56, 'value' => 'XL'],
            ['product_id' => 22, 'category_attribute_value_id' => 57, 'value' => 'Trắng'],
            ['product_id' => 22, 'category_attribute_value_id' => 57, 'value' => 'Đen'],
            ['product_id' => 22, 'category_attribute_value_id' => 58, 'value' => 'L'],
            ['product_id' => 22, 'category_attribute_value_id' => 58, 'value' => 'XL'],
            ['product_id' => 23, 'category_attribute_value_id' => 57, 'value' => 'Xanh'],
            ['product_id' => 23, 'category_attribute_value_id' => 57, 'value' => 'Nâu'],
            ['product_id' => 23, 'category_attribute_value_id' => 58, 'value' => 'L'],
            ['product_id' => 23, 'category_attribute_value_id' => 58, 'value' => 'XL'],
            ['product_id' => 24, 'category_attribute_value_id' => 59, 'value' => 'Trắng'],
            ['product_id' => 24, 'category_attribute_value_id' => 59, 'value' => 'Đen'],
            ['product_id' => 24, 'category_attribute_value_id' => 60, 'value' => 'M'],
            ['product_id' => 24, 'category_attribute_value_id' => 60, 'value' => 'L'],
            ['product_id' => 24, 'category_attribute_value_id' => 60, 'value' => 'XL'],
            ['product_id' => 25, 'category_attribute_value_id' => 59, 'value' => 'Trắng'],
            ['product_id' => 25, 'category_attribute_value_id' => 59, 'value' => 'Đen'],
            ['product_id' => 25, 'category_attribute_value_id' => 60, 'value' => 'M'],
            ['product_id' => 25, 'category_attribute_value_id' => 60, 'value' => 'L'],
            ['product_id' => 26, 'category_attribute_value_id' => 61, 'value' => 'Trắng'],
            ['product_id' => 26, 'category_attribute_value_id' => 61, 'value' => 'Đen'],
            ['product_id' => 26, 'category_attribute_value_id' => 62, 'value' => 'M'],
            ['product_id' => 26, 'category_attribute_value_id' => 62, 'value' => 'L'],
            ['product_id' => 27, 'category_attribute_value_id' => 61, 'value' => 'Trắng'],
            ['product_id' => 27, 'category_attribute_value_id' => 61, 'value' => 'Đen'],
            ['product_id' => 27, 'category_attribute_value_id' => 62, 'value' => 'M'],
            ['product_id' => 27, 'category_attribute_value_id' => 62, 'value' => 'L'],
            ['product_id' => 28, 'category_attribute_value_id' => 63, 'value' => 'Trắng'],
            ['product_id' => 28, 'category_attribute_value_id' => 63, 'value' => 'Hồng'],
            ['product_id' => 28, 'category_attribute_value_id' => 64, 'value' => 'M'],
            ['product_id' => 28, 'category_attribute_value_id' => 64, 'value' => 'L'],
            ['product_id' => 29, 'category_attribute_value_id' => 65, 'value' => 'Xanh'],
            ['product_id' => 29, 'category_attribute_value_id' => 65, 'value' => 'Trắng'],
            ['product_id' => 29, 'category_attribute_value_id' => 66, 'value' => '26'],
            ['product_id' => 29, 'category_attribute_value_id' => 66, 'value' => '27'],
            ['product_id' => 29, 'category_attribute_value_id' => 66, 'value' => '28'],
            ['product_id' => 30, 'category_attribute_value_id' => 67, 'value' => 'Đen'],
            ['product_id' => 30, 'category_attribute_value_id' => 67, 'value' => 'Xanh'],
            ['product_id' => 30, 'category_attribute_value_id' => 68, 'value' => '26'],
            ['product_id' => 30, 'category_attribute_value_id' => 68, 'value' => '27'],
            ['product_id' => 30, 'category_attribute_value_id' => 68, 'value' => '28'],
            ['product_id' => 31, 'category_attribute_value_id' => 73, 'value' => 'Đen'],
            ['product_id' => 31, 'category_attribute_value_id' => 73, 'value' => 'Xanh'],
            ['product_id' => 31, 'category_attribute_value_id' => 74, 'value' => '33'],
            ['product_id' => 31, 'category_attribute_value_id' => 74, 'value' => '34'],
            ['product_id' => 31, 'category_attribute_value_id' => 74, 'value' => '35'],
            ['product_id' => 32, 'category_attribute_value_id' => 75, 'value' => 'Vàng'],
            ['product_id' => 32, 'category_attribute_value_id' => 75, 'value' => 'Trắng'],
            ['product_id' => 32, 'category_attribute_value_id' => 76, 'value' => '34'],
            ['product_id' => 32, 'category_attribute_value_id' => 76, 'value' => '35'],
            ['product_id' => 33, 'category_attribute_value_id' => 49, 'value' => 'Nâu'],
            ['product_id' => 33, 'category_attribute_value_id' => 49, 'value' => 'Xanh'],
            ['product_id' => 33, 'category_attribute_value_id' => 50, 'value' => 'Free Size'],
            ['product_id' => 34, 'category_attribute_value_id' => 79, 'value' => 'Nâu'],
            ['product_id' => 34, 'category_attribute_value_id' => 79, 'value' => 'Đen'],
            ['product_id' => 34, 'category_attribute_value_id' => 80, 'value' => '38'],
            ['product_id' => 34, 'category_attribute_value_id' => 80, 'value' => '39'],
            ['product_id' => 34, 'category_attribute_value_id' => 80, 'value' => '40'],
            ['product_id' => 35, 'category_attribute_value_id' => 6, 'value' => 'Trắng'],
            ['product_id' => 35, 'category_attribute_value_id' => 6, 'value' => 'Đỏ'],
            ['product_id' => 35, 'category_attribute_value_id' => 6, 'value' => 'Vàng'],
            ['product_id' => 36, 'category_attribute_value_id' => 7, 'value' => 'Trắng'],
            ['product_id' => 36, 'category_attribute_value_id' => 7, 'value' => 'Đen'],
            ['product_id' => 36, 'category_attribute_value_id' => 7, 'value' => 'Vàng'],
            ['product_id' => 37, 'category_attribute_value_id' => 9, 'value' => 'Trắng'],
            ['product_id' => 37, 'category_attribute_value_id' => 9, 'value' => 'Đỏ'],
            ['product_id' => 37, 'category_attribute_value_id' => 9, 'value' => 'Đen'],
            ['product_id' => 37, 'category_attribute_value_id' => 10, 'value' => '15"'],
            ['product_id' => 38, 'category_attribute_value_id' => 11, 'value' => 'Đen'],
            ['product_id' => 38, 'category_attribute_value_id' => 11, 'value' => 'Trắng'],
            ['product_id' => 38, 'category_attribute_value_id' => 11, 'value' => 'Đỏ'],
            ['product_id' => 38, 'category_attribute_value_id' => 12, 'value' => '16"'],
            ['product_id' => 39, 'category_attribute_value_id' => 11, 'value' => 'Trắng'],
            ['product_id' => 39, 'category_attribute_value_id' => 11, 'value' => 'Đen'],
            ['product_id' => 39, 'category_attribute_value_id' => 11, 'value' => 'Đỏ'],
            ['product_id' => 39, 'category_attribute_value_id' => 12, 'value' => '16"'],
            ['product_id' => 40, 'category_attribute_value_id' => 2, 'value' => 'Trắng'],
            ['product_id' => 40, 'category_attribute_value_id' => 2, 'value' => 'Đỏ'],
            ['product_id' => 40, 'category_attribute_value_id' => 2, 'value' => 'Đen'],
            ['product_id' => 41, 'category_attribute_value_id' => 3, 'value' => 'Trắng'],
            ['product_id' => 41, 'category_attribute_value_id' => 3, 'value' => 'Đen'],
            ['product_id' => 41, 'category_attribute_value_id' => 3, 'value' => 'Đỏ'],
            ['product_id' => 42, 'category_attribute_value_id' => 2, 'value' => 'Trắng'],
            ['product_id' => 42, 'category_attribute_value_id' => 2, 'value' => 'Đỏ'],
            ['product_id' => 42, 'category_attribute_value_id' => 2, 'value' => 'Vàng'],
            ['product_id' => 43, 'category_attribute_value_id' => 3, 'value' => 'Trắng'],
            ['product_id' => 43, 'category_attribute_value_id' => 3, 'value' => 'Đen'],
            ['product_id' => 44, 'category_attribute_value_id' => 19, 'value' => 'Đen'],
            ['product_id' => 44, 'category_attribute_value_id' => 19, 'value' => 'Trắng'],
            ['product_id' => 44, 'category_attribute_value_id' => 20, 'value' => 'L'],
            ['product_id' => 44, 'category_attribute_value_id' => 20, 'value' => 'XL'],
            ['product_id' => 46, 'category_attribute_value_id' => 75, 'value' => 'Trắng'],
            ['product_id' => 46, 'category_attribute_value_id' => 75, 'value' => 'Đen'],
            ['product_id' => 46, 'category_attribute_value_id' => 75, 'value' => 'Xanh'],
            ['product_id' => 46, 'category_attribute_value_id' => 76, 'value' => '33'],
            ['product_id' => 46, 'category_attribute_value_id' => 76, 'value' => '34'],
            ['product_id' => 46, 'category_attribute_value_id' => 76, 'value' => '35']
        ]);
    }
}
